default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: thuan274
  password: 1212
  host: localhost

development:
  <<: *default
  database: books_development

test:
  <<: *default
  database: books_test

production:
  <<: *default
  database: broll_production
  username: broll
  password: <%= ENV['BROLL_DATABASE_PASSWORD'] %>
